In [21]:
import pandas as pd
import numpy as np

MI = pd.read_csv('MI.csv',header=2)
MI

Obs #  Size  Volatility   POV  LnMktCap  Cost_bp
0         1  0.12        0.37  0.36     16.48   115.41
1         2  0.01        0.32  0.04     15.09     9.06
2         3  0.08        0.46  0.22     21.70    81.57
3         4  0.21        0.37  0.36     28.53   139.22
4         5  0.11        0.43  0.09     20.22    43.22
5         6  0.32        0.46  0.39     16.71   124.46
6         7  0.31        0.31  0.57     27.04   158.34
7         8  0.04        0.38  0.23     28.79    58.73
8         9  0.18        0.33  0.17     15.23    61.80
9        10  0.21        0.32  0.33     17.26   116.21
10       11  0.06        0.43  0.51     22.80   117.26
11       12  0.27        0.45  0.47     23.21   144.57
12       13  0.11        0.49  0.31     16.09   121.67
13       14  0.13        0.32  0.48     21.69    85.01
14       15  0.35        0.34  0.33     25.66   107.00
15       16  0.20        0.35  0.54     20.64   150.42
16       17  0.13        0.31  0.43     16.41    83.88
17       18  0.15        0.42  0.55     21.83   169.11
18       19  0.24        0.45  0.32     16.63   117.37
19       20  0.14        0.42  0.18     29.28    61.11
20       21  0.07        0.42  0.28     20.10    89.17
21       22  0.12        0.38  0.23     24.32    57.96
22       23  0.32        0.40  0.17     26.79    73.42
23       24  0.29        0.36  0.33     16.18    87.15
24       25  0.11        0.35  0.16     27.26    56.40
25       26  0.23        0.41  0.41     23.07   100.30
26       27  0.33        0.47  0.52     23.42   185.48
27       28  0.24        0.37  0.42     22.92   163.45
28       29  0.19        0.40  0.30     22.15    84.69
29       30  0.01        0.33  0.12     17.26    16.18
...     ...   ...         ...   ...       ...      ...
2470   2471  0.04        0.43  0.09     24.39    19.64
2471   2472  0.08        0.39  0.22     18.63    49.32
2472   2473  0.13        0.31  0.51     24.55    85.90
2473   2474  0.23        0.47  0.21     19.77    74.32
2474   2475  0.07        0.48  0.04     24.86    19.04
2475   2476  0.14        0.45  0.48     26.13   173.77
2476   2477  0.24        0.49  0.15     15.54    70.04
2477   2478  0.06        0.44  0.57     29.17    92.35
2478   2479  0.08        0.34  0.52     19.46    92.69
2479   2480  0.27        0.42  0.45     18.93   150.81
2480   2481  0.04        0.32  0.39     18.59    78.40
2481   2482  0.20        0.38  0.48     26.81    96.76
2482   2483  0.19        0.44  0.28     16.08   127.60
2483   2484  0.25        0.46  0.18     17.43    84.06
2484   2485  0.28        0.43  0.19     23.38   105.17
2485   2486  0.02        0.50  0.13     28.27    35.51
2486   2487  0.18        0.43  0.14     23.30    53.13
2487   2488  0.08        0.41  0.30     27.49    83.82
2488   2489  0.20        0.42  0.29     24.45   118.84
2489   2490  0.22        0.36  0.42     23.68   121.10
2490   2491  0.34        0.42  0.47     22.10   130.61
2491   2492  0.23        0.33  0.42     19.70   135.82
2492   2493  0.17        0.43  0.13     26.25    45.75
2493   2494  0.25        0.34  0.48     29.64   113.84
2494   2495  0.25        0.39  0.45     29.42   107.70
2495   2496  0.14        0.49  0.34     20.71    94.58
2496   2497  0.20        0.50  0.49     19.88   119.87
2497   2498  0.05        0.47  0.56     27.99   109.36
2498   2499  0.24        0.46  0.47     23.77   156.71
2499   2500  0.16        0.48  0.49     29.69   141.92

[2500 rows x 6 columns]

In [22]:
MI.shape

(2500, 6)

In [18]:
r = np.random.RandomState(1234)


In [35]:
MI_s = MI.sample(n=10,replace =True,random_state=r)
MI_s

Obs #  Size  Volatility   POV  LnMktCap  Cost_bp
2168   2169  0.33        0.36  0.43     26.38   178.50
1904   1905  0.20        0.41  0.21     29.09    89.16
969     970  0.13        0.47  0.07     26.42    32.70
2431   2432  0.09        0.32  0.45     26.28    87.22
246     247  0.01        0.50  0.05     18.17    15.57
1586   1587  0.19        0.46  0.41     28.27   134.79
1787   1788  0.32        0.38  0.31     27.84   132.16
1100   1101  0.25        0.33  0.26     18.28    94.06
2341   2342  0.26        0.41  0.55     22.06   123.03
1826   1827  0.10        0.50  0.55     19.09   119.99

In [30]:
Y = MI_s['Cost_bp'].values
size = MI_s['Size'].values
volatility = MI_s['Volatility'].values
POV = MI_s['POV'].values
LnMktCap = MI_s['LnMktCap'].values
LnMktCap

array([ 27.8 ,  16.99,  26.74,  18.05,  22.12,  18.73,  24.02,  21.62,
        17.67,  22.1 ])

In [50]:
def model(size,volatility,POV, LnMktCap, coeffs):
    return coeffs[0]*(size**coeffs[1])*(volatility**coeffs[2])*(LnMktCap**coeffs[4]) *  (coeffs[5]*POV **coeffs[3]   + (1-coeffs[3] ))

#coeffs[0] is a1
#coeffs[1] is a2
#coeffs[2] is a3
#coeffs[3] is a4
#coeffs[4] is a5
#coeffs[5] is b1

x0 = np.array([3, 30, 15, 1,4,5], dtype=float)  # An approximative initial solution that we can find from looking at the graph is for instance:

def residuals(coeffs, y,size,volatility,POV, LnMktCap):
    return y - model(size,volatility,POV, LnMktCap, coeffs)

from scipy.optimize import leastsq
x, flag = leastsq(residuals, x0, args=(size,volatility,POV, LnMktCap,Y ))
print(x)


[ 0.66762331  1.70944885  0.10205228 -0.02788472  0.90846794 -1.08957932]


C:\Users\bjd\Anaconda3\envs\py2.7\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: overflow encountered in power
  from ipykernel import kernelapp as app
C:\Users\bjd\Anaconda3\envs\py2.7\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: overflow encountered in multiply
  from ipykernel import kernelapp as app


In [43]:
import numpy as np
from scipy.optimize import curve_fit

xdata = np.array([-2,-1.64,-1.33,-0.7,0,0.45,1.2,1.64,2.32,2.9])
ydata = np.array([0.699369,0.700462,0.695354,1.03905,1.97389,2.41143,1.91091,0.919576,-0.730975,-1.42001])

def func(x, p1,p2):
  return p1*np.cos(p2*x) + p2*np.sin(p1*x)

popt, pcov = curve_fit(func, xdata, ydata,p0=(1.0,0.2))
print popt
print "++++"
print pcov

[ 1.88185099  0.70022986]
++++
[[  7.52408287e-04   1.00812823e-04]
 [  1.00812823e-04   8.37695697e-05]]


In [29]:
from scipy.optimize import leastsq
help(leastsq)

Help on function leastsq in module scipy.optimize.minpack:

leastsq(func, x0, args=(), Dfun=None, full_output=0, col_deriv=0, ftol=1.49012e-08, xtol=1.49012e-08, gtol=0.0, maxfev=0, epsfcn=None, factor=100, diag=None)
    Minimize the sum of squares of a set of equations.
    
    ::
    
        x = arg min(sum(func(y)**2,axis=0))
                 y
    
    Parameters
    ----------
    func : callable
        should take at least one (possibly length N vector) argument and
        returns M floating point numbers. It must not return NaNs or
        fitting might fail.
    x0 : ndarray
        The starting estimate for the minimization.
    args : tuple, optional
        Any extra arguments to func are placed in this tuple.
    Dfun : callable, optional
        A function or method to compute the Jacobian of func with derivatives
        across the rows. If this is None, the Jacobian will be estimated.
    full_output : bool, optional
        non-zero to return all optional outputs.
